### ISSUE TITLE
Can't build example

### ISSUE THREAD

**Issue by nullsysvoid** [Curve/rohrkabel#5]
build/_deps/rohrkabel-src/include/rohrkabel/context.hpp:26:45: error: declaration of ‘std::shared_ptr<pipewire::core> pipewire::context::core()’ changes meaning of ‘core’ [-fpermissive]
[build]    26 |         [[nodiscard]] std::shared_ptr<core> core();

**Comment by Curve** [comment]
> build/_deps/rohrkabel-src/include/rohrkabel/context.hpp:26:45: error: declaration of ‘std::shared_ptr<pipewire::core> pipewire::context::core()’ changes meaning of ‘core’ [-fpermissive]
> [build]    26 |         [[nodiscard]] std::shared_ptr<core> core();

Will have a look

**Comment by Curve** [comment]
What compiler are you using?

**Comment by Curve** [comment]
Fixed ^^
