### ISSUE TITLE
interop with native api

### ISSUE THREAD

**Issue by 17steen** [Curve/rohrkabel#8]
is it possible to use the c-types to create wrapper objects?

eg:

```cpp
    auto pw_loop = pw::main_loop::create();
    auto pw_context = pw::context::create(pw_loop);
    // call not-wrapped c api
    auto* core_ptr = pw_context_connect_fd(pw_context->get(), remote_fd, nullptr, 0);
    auto core = pw::core::from(core_ptr); // takes ownership
```

**Comment by Curve** [comment]
Currently all types, **except** `loop`, `core`, registry` and `context` can be created from the raw c-type.

Reason being that e.g. the loop needs `pw_init` to be called, and the others depend on the life-time of another, thus they're currently not exposed.

Having a nice way of taking over / wrapping existing raw-types is still on my TODO list :)

**Comment by 17steen** [comment]
okay so unfortunately, this specifc use case isn't covered by the library yet,

anyway i could help?

**Comment by Curve** [comment]
> okay so unfortunately, this specifc use case isn't covered by the library yet,
> 
> anyway i could help?

I actually wanted to implement this right away, however the pipewire docs are currently down due to maintenance: 
![image](https://github.com/Curve/rohrkabel/assets/37805707/108de3c7-23ab-4b16-ae70-16acf7b5f48c)

**Comment by 17steen** [comment]
haha yes i saw too

i can install `sudo apt install pipewire-doc` then i get the website at /usr/share/doc/pipewire/html/index.html

**Comment by Curve** [comment]
Sorry, didn't get to it yet, will tackle this tomorrow :)

**Comment by Curve** [comment]
@17steen I've added a few ways to take-over or wrap (without taking ownership) existing raw-types :)

The update introduced multiple breaking changes, let me know if the introduced changes work for your use case!
