### ISSUE TITLE
[Request] Volume Example

### ISSUE THREAD

**Issue by ddanilov** [Curve/rohrkabel#9]
it would be nice to have, along with the `mute` example, API and corresponding example for volume, i.e. how to get/set volume for a channel of selected device.

**Comment by Curve** [comment]
The API for this already exists, it's the same principle as with mute,  but a little more cumbersome - I'll add an example soon

**Comment by Curve** [comment]
I've cleaned up the `spa::pod` APIs a little and added a [volume example](https://github.com/Curve/rohrkabel/tree/master/examples/volume) for devices :)
